# create root .my.cnf config file


## Need to install asible community ansible-galaxy collection install community.mysql

- name: add mysql python support for RedHat family
  yum: name=MySQL-python state=installed
  when: ansible_os_family == 'RedHat'
# - name: add mysql python support for Debian family
#   apt:  name=python-mysqldb state=installed
#   when: ansible_os_family == 'Debian'

- name: Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Mysql Root password 
  shell: grep "A temporary password" /var/log/mysqld.log  |awk '{print $13}'
  register:  password

- name: root | set root password
  shell: >-
      mysqladmin -u root
      --password="{{password.stdout}}"
      password "{{mysql_root_password}}"

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
